### ISSUE TITLE
Requirements sets configparser~=5.2.0 but update is 5.30. Why the limit?

### ISSUE THREAD

**Issue by WarthogARJ** [plandes/util#1]
Why is Util limited to (outdated) configparser 5.20 when the updated configparser is 5.3.0?

I saw the issue when I updated configparser to 5.30, and then ran pip check.
Which reported:
zensols-util 1.11.1 requires configparser~=5.2.0, but you have configparser 5.3.0 which is incompatible

I read your documentation and could not see why you limited the configparser version.
And I see that zotsite has same issue.

I am a noobie python user, and maybe there is an obvious reason for it.
But it makes it much harder to use python apps such as util if they cannot use the most recent (stable) dependency versions.

Excuse ignorance, but is the underlaying issue with util (and zotsite), or is there an issue with configparser?

I looked at configparser version history, and I cannot see why version 5.3.0 would break your apps.
configparser 5.30 changes are:
- Synced with Python 3.11.0rc1.
- Packaging refresh
- Requires Python 3.7 or later

To my (noobie) eyes, it seems configparser 5.3.0 is a much better version than 5.2.0 to peg something to, if you need to be careful about your app breaking with updates.

Thanks in any case for your efforts in writing these apps.

**Comment by plandes** [comment]
Hi @WarthogARJ,

The short answer: I'm more risk adverse when upgrading packages like configparser since its so heavily used (and the way it is used) in so many packages.

Long answer: by pinning it to a minor version means new installs or installing with -U only upgrades patched versions, which are bug fixes. The [convention](https://blog.inedo.com/python-best-practices-for-versioning-python-packages-in-the-enterprise) is that upgrading minor versions are backwards compatible.  However, in my experience, things break (and break often) when you're not careful and this involves everything related to configuration applications with the application context.  So I typically treat minor versions as feature upgrades. If I upgrade it, it has huge potential to break many applications for which I'll only find out later and in only in some edges cases.

On one hand, you could just ignore it and things will run fine. But, sometimes upgrading is inevitable and necessary.  Since I'm about to rerelease many packages, I have [upgraded](https://github.com/plandes/util/blob/master/CHANGELOG.md#1120---2023-01-22) it and all automated tests show things still work so I have released a new version of this package and [zotsite per your request](https://github.com/plandes/zotsite/blob/master/CHANGELOG.md#070---2023-01-22).  However, I will caveat that I will downgrade in a later version for any serious incompatibility.

Also, if you use the package, please star it.  I pay attention to the packages I know others are actually using.

Thanks for your input/feedback.
